[package]
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2021"
license = "Apache-2.0"
name = "rules_minidock_tools"
version = "0.1.0"


[[bin]]
name = "pusher-app"
path = "app/pusher_app.rs"


[[bin]]
name = "puller-app"
path = "app/puller_app.rs"


[[bin]]
name = "merge-app"
path = "app/merge_app.rs"

[dependencies]
anyhow = "1.0.70"
async-recursion = "1.0.4"
async-stream = "0.3.5"
async-trait = "0.1.68"
bytes = "1.4.0"
clap = { version = "4.2.1", features = ["derive", "env"] }
console = "0.15.5"
flate2 = "1.0.25"
futures-core = "0.3.28"
http = "0.2.9"
hyper = { version = "0.14.26", features = ["full"] }
hyper-rustls = "0.23.2"
indicatif = { git = "https://github.com/console-rs/indicatif.git", rev = "2ca9d019fbb4b0aed11bfad984daef064998f5ef" }
rustls = "0.20.8"
serde = { version = "1.0.160", features = ["derive", "alloc"] }
serde_json = { version = "1.0.96", features = ["alloc"] }
sha2 = "0.10.6"
tempfile = "3.4.0"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
tokio-stream = "0.1.12"
tokio-util = { version = "0.7.7", features = ["io"] }
tracing = "0.1.37"



[lib]
name = "rules_minidock_tools"
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.4.0"
