[package]
authors = ["Ian O'Connell <ianoc@ianoc.net>"]
edition = "2021"
license = "Apache-2.0"
name = "rules_minidock_tools"
version = "0.1.0"


[[bin]]
name = "pusher-app"
path = "app/pusher_app.rs"


[[bin]]
name = "puller-app"
path = "app/puller_app.rs"


[[bin]]
name = "merge-app"
path = "app/merge_app.rs"

[dependencies]
anyhow = "1.0.65"
async-recursion = "1.0.0"
async-stream = "0.3.3"
async-trait = "0.1.57"
bytes = "1.2.1"
clap = { version = "3.2.16", features = ["derive", "env"] }
console = "0.15.2"
flate2 = "1.0.24"
http = "0.2.8"
hyper = { version = "0.14.20", features = ["full"] }
hyper-rustls = "0.23.0"
indicatif = { git = "https://github.com/console-rs/indicatif.git", rev = "2ca9d019fbb4b0aed11bfad984daef064998f5ef" }
rustls = "0.20.6"
serde = { version = "1.0.145", features = ["derive", "alloc"] }
serde_json = { version = "1.0.83", features = ["alloc"] }
sha2 = "0.10.2"
tempfile = "3.3.0"
thiserror = "1.0.37"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.9"
tokio-util = { version = "0.7.4", features = ["io"] }
tracing = "0.1.36"



[lib]
name = "rules_minidock_tools"
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.3.0"
