name: Upload self-contained binaries

on:
  release:
    types: [published]

jobs:
  rust-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        platform: [x86_64]
        include:
          - os: macos-latest
            platform: x86_64
          - os: macos-latest
            platform: aarch64
          - os: ubuntu-latest
            platform: x86_64
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - name: Build and upload artifact
        run: ./.github/workflows/build_binaries.sh ${{ matrix.os }} ${{ matrix.platform }} merge-app puller-app pusher-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
