name: Test
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: macos
          - os: ubuntu-latest
            platform: linux
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - name: Run tests with all features
        run: cargo test --all-features
      - name: Run tests
        run: cargo test
